### ISSUE TITLE
wait-for-it.sh里，不是busybox的timeout，也没有-t参数

### ISSUE THREAD

**Issue by scoful** [Zhang-Xianglong/docker-entrypoint#1]
RT

**Comment by Zhang-Xianglong** [comment]
docker-entrypoint.sh脚本在CentOS 7 base image中验证可用。wait-for-it.sh是直接使用的https://github.com/vishnubob/wait-for-it

你的问题可能是由于BusyBox精简了一些命令的参数，你可以通过编写（自己的）或修改wait-for-it.sh，来适配使用BusyBox base image引起的问题。
另外，我查了一下BusyBox的文档，它的timeout命令是支持-t参数的，可能更新一下BusyBox base image的版本可以解决你这个问题。
